### ISSUE TITLE
Keep PyPI package up-to-date or add disclaimer to readme

### ISSUE THREAD

**Issue by sknebel** [striglia/stockfighter#12]
Right now, `pip install` still delivers a version of the library where terminating instances doesn't work. I know it is additional work, but if you recommend to use pip instead of just checking out the repo PyPI should be up to date.

**Comment by striglia** [comment]
Yep, no problem. Honestly it's hard to tell how many people are actually using it, so I was basically collecting bugfixes in master until I had a few or someone like you asked for a new release :)

I'll go ahead and tag+publish 0.2.7 now and close this issue once it's done.

**Comment by striglia** [comment]
All done!

**Comment by sknebel** [comment]
Thank you! :+1:
