### ISSUE TITLE
post requests break on requests < 2.4.2

### ISSUE THREAD

**Issue by dhaynespls** [striglia/stockfighter#13]
hey,

So apparently trying to post something (ie. place_new_order) while using a dated version of requests causes the reponse to return: 

> TypeError: request() got an unexpected keyword argument 'json'

I believe the default version installed on some machines (mine being ububntu 14.04) is requests 2.2.1 which breaks when 

> return requests.post(_args, *_kwargs)

is called since this shortcut for the longer post statement is only supported on requests >2.4.2.

In order to avoid users having this issue, we should put in the documentation that users need to be on requests version >2.4.2 (can just be "do this - pip install requests --upgrade or you could add a line in requirements.txt "requests=2.4.2" and have people do "pip install -r requirements.txt" in the getting started section. 

Not sure what would be the best way but wanted to report in what I have found.

**Comment by striglia** [comment]
Solid report, thanks!

The right fix here (so it applies for people just doing `pip install stockfighter`) is to figure out the proper minimum version requirements and put it directly into the setup.py install_requires section.

**Comment by striglia** [comment]
Looks like https://github.com/kennethreitz/requests/blob/master/HISTORY.rst is relevant, although I'm having trouble finding explicit mention of these issues. I'll probably just throw in 2.4.2 if I can't find any better place to draw the line...

**Comment by striglia** [comment]
Looks like https://github.com/kennethreitz/requests/commit/1e79cf6a47edc47968dc14221d8c8765ab8341c8. I'm going to go ahead and mark 2.4.2 as the minimum version.

Confirmed by pinning at 2.4.1 in setup.py and seeing `E       TypeError: request() got an unexpected keyword argument 'json'` when I ran tests. 2.4.2 works perfectly fine. Yay testing :)
