### ISSUE TITLE
place_new_order function missing price in data

### ISSUE THREAD

**Issue by richardlaborde** [striglia/stockfighter#4]
def place_new_order(self, stock, price, qty, direction, order_type):
        """Place an order for a stock.
        https://starfighter.readme.io/docs/place-new-order
        """
        url_fragment = 'venues/{venue}/stocks/{stock}/orders'.format(
            venue=self.venue,
            stock=stock,
        )
        data = {
          "stock": stock,
          "venue": self.venue,
          "account": self.account,
          "qty": qty,
          "direction": direction,
          "orderType": order_type,
        }

**Comment by striglia** [comment]
You don't say :) Let's get that fixed...

**Comment by striglia** [comment]
Solved in 0.2.6 and up at https://pypi.python.org/pypi/stockfighter. Thanks for bearing with me during alpha week! Hoping API key issues will be resolved soon so these functions can get a little integration testing....
